management:
  server:
    port: 1${server.port}
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    dubbo:
      enabled: true
    dubboshutdown:
      enabled: true
    dubboconfigs:
      enabled: true
    dubboservices:
      enabled: true
    dubboreferences:
      enabled: true
    dubboproperties:
      enabled: true