# hystrix
# com.netflix.hystrix.HystrixThreadPoolProperties
# com.netflix.hystrix.HystrixCommandProperties

vergilyn:
  custom:
    hystrix-timeout: 2000

hystrix:
  threadpool:
    default:
      coreSize: 20
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: ${vergilyn.custom.hystrix-timeout}
