management:
  server:
    port: 8081
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
      cache:
        time-to-live: 30s
    httptrace:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'   # * 在yaml 文件属于关键字，所以需要加引号

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4

# 通过定义`info.*`自定义spring-boot-actuator的`/actuator/info`返回信息。 默认访问返回`{}`
info:
  name: spring-boot-actuator-test
  version: 1.0.0
  author: vergilyn